application: test-results
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /testfile/delete
  script: main.py
  login: admin

- url: /dashboards/delete
  script: main.py
  login: admin

- url: /.*
  script: main.py
